schema: "classroom50/repo-config/v1"
classroom: "data-tech-analytics"
assignment: "hello-github"
owner:
  username: "Reshikagg"
  id: 229000602
  accepted_at: "2026-08-27T21:15:40Z"
source:
  owner: "IT4063C-Fall2026"
  owner_id: 320344006
  repo: "hello-github"
  branch: "main"
